# Generated by Django 2.2.9 on 2020-02-01 15:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import quote.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('tlc_number', models.CharField(max_length=6, verbose_name='TLC #')),
                ('tlc_name', models.CharField(max_length=255, verbose_name='TLC Name')),
                ('vehicle_vin', models.CharField(max_length=511, verbose_name='VIN #')),
                ('vehicle_owner', models.CharField(max_length=255, verbose_name='Vehicle Owner')),
                ('license_plate', models.CharField(max_length=20, verbose_name='License Plate #')),
                ('base_number', models.CharField(max_length=6, verbose_name='Base Number')),
                ('base_type', models.CharField(max_length=255, verbose_name='Base Number')),
                ('vehicle_year', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[1,2][0,9]\\d{2}$')], verbose_name='Vehicle Year')),
                ('vehicle_weight', models.CharField(blank=True, max_length=8, null=True, verbose_name='Vehicle Weight')),
                ('is_clean_air_vehicle', models.BooleanField(blank=True, null=True, verbose_name='Is Clean air vehicle')),
                ('insurance_carrier_name', models.CharField(max_length=255, verbose_name='Insurance Carrier Name')),
                ('insurance_policy_number', models.CharField(max_length=255, verbose_name='Policy Number')),
                ('tlc_license_years', models.CharField(choices=[('<1', '<1'), ('1-3', '1-3'), ('3+', '3+')], max_length=3, verbose_name='How long TLC License')),
                ('dmv_license_years', models.CharField(choices=[('<2', '<2'), ('2-3', '2-3'), ('3+', '3+')], max_length=3, verbose_name='How long DMV License')),
                ('driver_points_last_months', models.CharField(choices=[('0-6', '0-6'), ('7-10', '7-10'), ('10+', '10+')], max_length=4, verbose_name='Driver points in last 36 months')),
                ('defensive_driving_certificate', models.BooleanField(verbose_name='Defensive driving certificate')),
                ('accident_avoidance_system', models.BooleanField(verbose_name='Accident avoidance system')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Deposit Amount')),
                ('deposit', models.PositiveIntegerField(blank=True, choices=[(15, '15%'), (20, '20%'), (25, '25%')], null=True, verbose_name='Deposit')),
                ('deductible', models.PositiveIntegerField(blank=True, choices=[(750, '750'), (1000, '1000'), (1500, '1500')], null=True, verbose_name='Deductible')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Quote Process',
                'verbose_name_plural': 'Quote Processes',
            },
        ),
        migrations.CreateModel(
            name='QuoteProcessDocuments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('broker_of_record', models.FileField(blank=True, null=True, upload_to=quote.models.quote_process_document_upload_to, verbose_name='Broker of Record Change')),
                ('dmv_license_front_side', models.FileField(blank=True, null=True, upload_to=quote.models.quote_process_document_upload_to, verbose_name='DMV License Front Side')),
                ('dmv_license_back_side', models.FileField(blank=True, null=True, upload_to=quote.models.quote_process_document_upload_to, verbose_name='DMV License Back Side')),
                ('tlc_license_front_side', models.FileField(blank=True, null=True, upload_to=quote.models.quote_process_document_upload_to, verbose_name='DMV License Front Side')),
                ('tlc_license_back_side', models.FileField(blank=True, null=True, upload_to=quote.models.quote_process_document_upload_to, verbose_name='TLC License Back Side')),
                ('proof_of_address', models.FileField(blank=True, null=True, upload_to=quote.models.quote_process_document_upload_to, verbose_name='Proof of Address')),
                ('defensive_driving_certificate', models.FileField(blank=True, null=True, upload_to=quote.models.quote_process_document_upload_to, verbose_name='Defensive Driving Certificate')),
                ('is_submitted_for_review', models.BooleanField(default=False, verbose_name='Submmited for review')),
                ('quote_process', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quote.QuoteProcess', verbose_name='Quote Process')),
            ],
            options={
                'verbose_name': 'Quote Process Documents',
                'verbose_name_plural': 'Quote Process Documents',
            },
        ),
        migrations.CreateModel(
            name='QuoteProcessPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('official_hereford_quote', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Official Hereford Quote')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Payment Date')),
                ('quote_process', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quote.QuoteProcess', verbose_name='Quote Process')),
            ],
            options={
                'verbose_name': 'Quote Process Payment',
                'verbose_name_plural': 'Quote Process Payment',
            },
        ),
        migrations.CreateModel(
            name='QuoteProcessDocumentsAciddentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('defensive_driving_certificate', models.FileField(blank=True, null=True, upload_to=quote.models.quote_process_document_upload_to, verbose_name='Accident Report')),
                ('quote_process_documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.QuoteProcessDocuments', verbose_name='Quote Process Documents')),
            ],
            options={
                'verbose_name': 'Quote Process Documents Accident Report',
                'verbose_name_plural': 'Quote Process Documents Accident Report',
            },
        ),
    ]
