# Generated by Django 2.2.9 on 2020-02-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteprocess',
            name='vehicle_vin',
            field=models.CharField(max_length=17, verbose_name='VIN #'),
        ),
    ]
