# Generated by Django 2.2.9 on 2020-02-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_auto_20200201_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteprocess',
            name='base_type',
            field=models.CharField(max_length=255, verbose_name='Base Type'),
        ),
    ]
