# Generated by Django 2.2.9 on 2020-02-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_auto_20200201_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quoteprocess',
            options={'ordering': ('-created',), 'verbose_name': 'Quote Process', 'verbose_name_plural': 'Quote Processes'},
        ),
        migrations.AlterModelOptions(
            name='quoteprocessdocuments',
            options={'ordering': ('-created',), 'verbose_name': 'Quote Process Documents', 'verbose_name_plural': 'Quote Process Documents'},
        ),
        migrations.AlterModelOptions(
            name='quoteprocessdocumentsaciddentreport',
            options={'ordering': ('-created',), 'verbose_name': 'Quote Process Documents Accident Report', 'verbose_name_plural': 'Quote Process Documents Accident Report'},
        ),
    ]
