# Generated by Django 2.2.9 on 2020-02-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_auto_20200202_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteprocess',
            name='tlc_number',
            field=models.CharField(max_length=7, verbose_name='TLC #'),
        ),
    ]
