# Generated by Django 2.2.9 on 2020-02-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0006_auto_20200202_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteprocess',
            name='base_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Base Type'),
        ),
    ]
