# Generated by Django 2.2.9 on 2020-02-03 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0007_auto_20200203_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteprocess',
            name='vehicle_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('^[1,2][0,9]\\d{2}$')], verbose_name='Vehicle Year'),
        ),
    ]
