# Generated by Django 2.2.9 on 2020-02-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0008_auto_20200203_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteprocess',
            name='base_name',
            field=models.CharField(default='', max_length=511, verbose_name='Base Name'),
            preserve_default=False,
        ),
    ]
