# Generated by Django 2.2.10 on 2020-02-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0009_quoteprocess_base_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteprocess',
            name='fault_accidents_last_months',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3+', '3+')], default='', max_length=2, verbose_name='Fault accidents in last 36 months'),
            preserve_default=False,
        ),
    ]
