# Generated by Django 2.2.10 on 2020-02-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0011_quotesoftfallout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotesoftfallout',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Number'),
        ),
    ]
