# Generated by Django 2.2.9 on 2020-02-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0012_auto_20200206_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteprocess',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start date'),
        ),
    ]
