# Generated by Django 2.2.9 on 2020-02-09 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0019_auto_20200209_1531'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuoteProcessDocumentsAciddentReport',
            new_name='QuoteProcessDocumentsAccidentReport',
        ),
    ]
