# Generated by Django 2.2.9 on 2020-02-09 16:10

from django.db import migrations, models
import quote.models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0020_auto_20200209_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteprocessdocumentsaccidentreport',
            name='accident_report',
            field=models.FileField(blank=True, null=True, upload_to=quote.models.quote_process_document_accident_upload_to, verbose_name='Accident Report'),
        ),
    ]
