# Generated by Django 2.2.9 on 2020-02-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0022_auto_20200210_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteprocessdocuments',
            name='requires_broker_of_record',
            field=models.BooleanField(default=False, verbose_name='Require Broker of Record Change'),
        ),
    ]
