# Generated by Django 2.2.9 on 2020-02-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0023_quoteprocessdocuments_requires_broker_of_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteprocesspayment',
            name='liability_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Just in case you want to show the amount to the user', max_digits=7, null=True, verbose_name='Liability Amount'),
        ),
        migrations.AddField(
            model_name='quoteprocesspayment',
            name='physical_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Just in case you want to show the amount to the user', max_digits=7, null=True, verbose_name='Physical Amount'),
        ),
    ]
