# Generated by Django 2.2.9 on 2020-02-12 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('quote', '0024_auto_20200211_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteprocesspayment',
            name='stripe_charge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.StripeCharge', verbose_name='Stripe Charge'),
        ),
        migrations.AlterField(
            model_name='quoteprocess',
            name='deductible',
            field=models.PositiveIntegerField(blank=True, choices=[(750, '750'), (1000, '1000'), (1500, '1500')], null=True, verbose_name='Physical Coverage ($)'),
        ),
        migrations.AlterField(
            model_name='quoteprocess',
            name='deposit',
            field=models.PositiveIntegerField(blank=True, choices=[(15, '15%'), (20, '20%'), (25, '25%')], null=True, verbose_name='Deposit (%)'),
        ),
    ]
