# Generated by Django 2.2.9 on 2020-02-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0025_auto_20200212_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteprocess',
            name='accidents_72_months',
            field=models.CharField(choices=[('0', '0'), ('1-3', '1-3'), ('4+', '4+')], default=0, max_length=3, verbose_name='Accidents in last 72 months'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoteprocess',
            name='dash_cam',
            field=models.BooleanField(default=False, verbose_name='Dash Cam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoteprocess',
            name='dwi_36_months',
            field=models.BooleanField(default=False, verbose_name='DWI or DUI violation within the past 36 months'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoteprocess',
            name='fault_accident_pedestrian',
            field=models.BooleanField(default=False, verbose_name='Fault accident w/ pedestrian/bicyclist 24 months'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoteprocess',
            name='speeding_violation',
            field=models.BooleanField(default=False, verbose_name='Speeding violation > 30 MPH within the last 24 months'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoteprocess',
            name='vehicle_is_hybrid',
            field=models.BooleanField(default=False, verbose_name='Vehicle is hybrid'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quoteprocess',
            name='dmv_license_years',
            field=models.CharField(choices=[('<1', '<1'), ('1-2', '1-2'), ('3+', '3+')], max_length=3, verbose_name='How long DMV License'),
        ),
    ]
