# Generated by Django 2.2.9 on 2020-02-12 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0027_auto_20200212_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteprocess',
            name='base_type',
        ),
    ]
