# Generated by Django 2.2.9 on 2020-02-12 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0005_auto_20200212_2209'),
        ('quote', '0028_remove_quoteprocess_base_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteprocess',
            name='base_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='importer.BaseType', verbose_name='Base Type'),
        ),
    ]
