# Generated by Django 2.2.10 on 2020-02-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0030_auto_20200213_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteprocess',
            name='deposit',
            field=models.PositiveIntegerField(blank=True, choices=[(15, '15%'), (20, '20%'), (25, '25%'), (40, '40%')], null=True, verbose_name='Deposit (%)'),
        ),
    ]
