# Generated by Django 2.2.10 on 2020-02-13 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0031_auto_20200213_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendQuoteProcessPayment',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('quote.quoteprocesspayment',),
        ),
    ]
