# Generated by Django 2.2.9 on 2020-02-13 15:17

from django.db import migrations, models
import quote.models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0031_auto_20200213_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteprocessdocuments',
            name='base_letter',
            field=models.FileField(blank=True, null=True, upload_to=quote.models.quote_process_document_upload_to, verbose_name='Base Letter'),
        ),
    ]
