# Generated by Django 2.2.9 on 2020-02-13 17:28

from django.db import migrations, models


def populate_is_hereford(apps, schema_editor):
  QuoteProcess = apps.get_model('quote', 'QuoteProcess')
  for quote in QuoteProcess.objects.all():
    quote.is_hereford = "hereford" in quote.insurance_carrier_name.lower()
    quote.save()

class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0032_quoteprocessdocuments_base_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteprocess',
            name='is_hereford',
            field=models.BooleanField(default=False, verbose_name='Is Hereford'),
        ),
        migrations.RunPython(populate_is_hereford, migrations.RunPython.noop)
    ]
