# Generated by Django 2.2.9 on 2020-02-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0034_auto_20200213_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteprocess',
            name='deposit',
            field=models.PositiveIntegerField(blank=True, choices=[(15, '15%'), (20, '20%'), (25, '25%'), (40, '40%'), (100, '100%')], null=True, verbose_name='Deposit (%)'),
        ),
    ]
