# Generated by Django 2.2.10 on 2020-02-20 12:37

from django.db import migrations, models
import quote.models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0035_quoteprocessdocuments_hsr'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteprocessdocuments',
            name='broker_record_file',
            field=models.FileField(blank=True, null=True, upload_to=quote.models.quote_process_document_upload_to, verbose_name='Broker Record Signed'),
        ),
    ]
