# Generated by Django 2.2.10 on 2020-02-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0036_quoteprocesspayment_deposit_payment_amount'),
        ('quote', '0032_sendquoteprocesspayment'),
    ]

    operations = [
    ]
