# Generated by Django 2.2.9 on 2020-02-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0037_merge_20200226_0926'),
        ('quote', '0036_quoteprocessdocuments_broker_record_file'),
    ]

    operations = [
    ]
