# Generated by Django 2.2.10 on 2020-03-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0039_auto_20200227_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteprocesspayment',
            name='deposit_percentage',
            field=models.PositiveIntegerField(blank=True, choices=[(15, '15%'), (20, '20%'), (25, '25%'), (40, '40%'), (100, '100%')], null=True, verbose_name='Deposit (%)'),
        ),
        migrations.AddField(
            model_name='quoteprocesspayment',
            name='has_third_party_deposit',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Has Third Party Deposit Coverage'),
        ),
        migrations.AddField(
            model_name='quoteprocesspayment',
            name='third_party_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Third Party Covered Amount'),
        ),
        migrations.AddField(
            model_name='quoteprocesspayment',
            name='third_party_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Third Party Name'),
        ),
    ]
