# Generated by Django 2.2.14 on 2020-07-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0040_add_thirdparty_deposit_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteprocessdocuments',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
