# Generated by Django 2.2.10 on 2020-02-19 12:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import hellosign_app.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelloSignSavedCallback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('post', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='post')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='data')),
                ('body', models.TextField(default='', verbose_name='body')),
                ('traceback', models.TextField(default='', null=True, verbose_name='traceback')),
                ('caller', models.TextField(default='hellosign_app', verbose_name='caller')),
            ],
            options={
                'verbose_name': 'hellosign_app callback',
                'verbose_name_plural': 'hellosign_app callbacks',
            },
        ),
        migrations.CreateModel(
            name='HelloSignSignatureRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('signature_request_id', models.CharField(blank=True, max_length=255, verbose_name='signature request id')),
                ('user_signature_id', models.CharField(blank=True, max_length=255, verbose_name='user_signature_id signature id')),
                ('user_signed', models.BooleanField(default=False, verbose_name='user signed')),
                ('signed_document', models.FileField(blank=True, max_length=1000, null=True, upload_to=hellosign_app.models.signed_document_path, verbose_name='document')),
            ],
            options={
                'verbose_name': 'HelloSign signature request',
                'verbose_name_plural': 'HelloSign signature requests',
                'ordering': ('-created',),
            },
        ),
    ]
