# Generated by Django 2.2.9 on 2020-02-01 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import policy.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quote', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('policy_number', models.CharField(max_length=255, verbose_name='Policy Number')),
                ('certifcate_of_liability', models.FileField(upload_to=policy.models.policy_document_upload_to, verbose_name='Certificate of Liability')),
                ('fh1_document', models.FileField(upload_to=policy.models.policy_document_upload_to, verbose_name='FH1 Document')),
                ('insurance_document', models.FileField(upload_to=policy.models.policy_document_upload_to, verbose_name='Insurance Document')),
                ('tlc_number', models.CharField(max_length=6, verbose_name='TLC #')),
                ('vehicle_vin', models.CharField(max_length=511, verbose_name='VIN #')),
                ('license_plate', models.CharField(max_length=20, verbose_name='License Plate #')),
                ('quote_process', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quote.QuoteProcess', verbose_name='Quote Process')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
            },
        ),
    ]
