# Generated by Django 2.2.10 on 2020-02-13 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_auto_20200213_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='license_plate',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='tlc_number',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='vehicle_vin',
        ),
    ]
