# Generated by Django 2.2.10 on 2020-02-13 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_auto_20200213_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePolicy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('policy.policy',),
        ),
    ]
