# Generated by Django 2.2.10 on 2020-02-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0004_createpolicy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='certifcate_of_liability',
            new_name='certificate_of_liability',
        ),
    ]
