# Generated by Django 2.2.10 on 2020-03-09 17:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('policy', '0005_auto_20200217_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('payment_due_date', models.DateField(blank=True, null=True, verbose_name='Payment Due Date')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Payment Date')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Payment Amount')),
                ('fee_amount', models.DecimalField(decimal_places=2, help_text='Change this if you want to change the fee amount for all the unpaid payments.', max_digits=7, verbose_name='Fee Amount')),
                ('is_deposit', models.BooleanField(default=False, verbose_name='Is Deposit')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.Policy', verbose_name='Policy')),
                ('stripe_charge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.StripeCharge', verbose_name='Stripe Charge')),
            ],
            options={
                'ordering': ['payment_due_date'],
                'verbose_name': 'Policy Payment',
                'verbose_name_plural': 'Policy Payments'
            },
        ),
        migrations.AddField(
            model_name='policy',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Fee Amount'),
        ),
    ]
