# Generated by Django 2.2.10 on 2020-03-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0007_generate_policy_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='autopay',
            field=models.BooleanField(default=False, verbose_name='Autopay'),
        ),
    ]
