STRIPE_PAYMENT_CHARGE_SUCCESS = "succeeded"
STRIPE_PAYMENT_CHARGE_PENDING = "pending"
STRIPE_PAYMENT_CHARGE_FAILED = "failed"

STRIPE_EVENT_STATUS_UNPROCESSED = "UNPROCESSED"
STRIPE_EVENT_STATUS_PROCESSED = "PROCESSED"
STRIPE_EVENT_STATUS_ERROR = "ERROR"
STRIPE_EVENT_STATUS_UNHANDLED = "UNHANDLED"

STRIPE_EVENT_STATUSES = (
    (STRIPE_EVENT_STATUS_UNPROCESSED, "Unprocessed"),
    (STRIPE_EVENT_STATUS_PROCESSED, "Processed"),
    (STRIPE_EVENT_STATUS_ERROR, "Error"),
    (STRIPE_EVENT_STATUS_UNHANDLED, "Unhandled"),
)

STRIPE_PERCENTAGE_FEE = 0.029 # 0-1
STRIPE_FIXED_FEE = 0.30 # Dollars
PLAID_FEE = 0 # Dollars