# Generated by Django 2.2.9 on 2020-02-02 18:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FHVActiveDriver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('raw_hash', models.CharField(db_index=True, editable=False, max_length=32)),
                ('raw', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Raw data')),
                ('license_number', models.CharField(max_length=511, verbose_name='License number')),
                ('name', models.CharField(max_length=511, verbose_name='Name')),
                ('fhv_type', models.CharField(max_length=511, verbose_name='Type')),
                ('expiration_date', models.DateField(verbose_name='Expiration date')),
                ('last_date_updated', models.DateField(verbose_name='Last date updated')),
                ('last_time_updated', models.TimeField(verbose_name='Last time updated')),
            ],
            options={
                'verbose_name': 'FHV Active Driver',
                'verbose_name_plural': 'FHV Active Drivers',
            },
        ),
        migrations.AddIndex(
            model_name='fhvactivedriver',
            index=models.Index(fields=['license_number'], name='importer_fh_license_ff5180_idx'),
        ),
        migrations.AddIndex(
            model_name='fhvactivedriver',
            index=models.Index(fields=['name', 'license_number'], name='importer_fh_name_d5f539_idx'),
        ),
    ]
