# Generated by Django 2.2.9 on 2020-02-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_auto_20200202_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhvactivedriver',
            name='wheelchair_accessible_trained',
            field=models.CharField(default='', max_length=511, verbose_name='Wheelchair Accesible Trained'),
            preserve_default=False,
        ),
    ]
