# Generated by Django 2.2.9 on 2020-02-12 22:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0003_fhvactivedriver_wheelchair_accessible_trained'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('base_number', models.CharField(max_length=6, verbose_name='Base number')),
                ('base_name', models.CharField(max_length=511, verbose_name='Base name')),
                ('base_type', models.CharField(choices=[('livery', 'Livery'), ('blackcar', 'Black Car')], max_length=8, verbose_name='Base type')),
                ('luxury_discount', models.BooleanField(default=False, verbose_name='Luxury discount')),
                ('loss_control_discount', models.BooleanField(default=False, verbose_name='Loss control discount')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
