# Generated by Django 2.2.9 on 2020-02-12 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import payment.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('stripe_id', models.CharField(max_length=511, verbose_name='Stripe ID')),
                ('livemode', models.BooleanField(verbose_name='Livemode')),
                ('last_default_source_id', models.CharField(default='', max_length=511, verbose_name='Last default source id')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Stripe Customer',
                'verbose_name_plural': 'Stripe Customers',
            },
        ),
        migrations.CreateModel(
            name='StripeCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('stripe_id', models.CharField(max_length=511, verbose_name='Stripe ID')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('livemode', models.BooleanField(verbose_name='Livemode')),
                ('amount', payment.fields.StripeDecimalCurrencyAmountField(decimal_places=2, max_digits=8, verbose_name='Amount')),
                ('paid', models.BooleanField(verbose_name='Paid')),
                ('status', models.CharField(max_length=511, verbose_name='Status')),
                ('source_id', models.CharField(blank=True, max_length=511, verbose_name='Source ID')),
                ('source_type', models.CharField(max_length=511, verbose_name='Source Type')),
                ('customer_id', models.CharField(blank=True, max_length=511, verbose_name='Customer ID')),
                ('receipt_url', models.URLField(verbose_name='Receipt URL')),
                ('product', models.UUIDField(default=uuid.uuid4, verbose_name='Product paid')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Stripe Charge',
                'verbose_name_plural': 'Stripe Charges',
            },
        ),
    ]
