# Generated by Django 2.2.12 on 2020-05-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecharge',
            name='receipt_url',
            field=models.URLField(blank=True, null=True, verbose_name='Receipt URL'),
        ),
    ]
