# Generated by Django 2.2.10 on 2020-02-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_create_admin_emails_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='magiclink',
            name='valid_forever',
            field=models.BooleanField(default=False, verbose_name='valid forever'),
        ),
    ]
