# Generated by Django 2.2.10 on 2020-03-23 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_magiclink_valid_forever'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasswordLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('expire_on', models.DateTimeField(default=users.models.magic_link_expire, verbose_name='expire on')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
